import Footer from '@/components/Footer'
import Header from '@/components/Header'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Audiophile',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body>
            <Header />
            {children}
            <Footer />    
        </body>
    </html>
  )
}
