"use client"
import Header from '@/components/Header'
import Hero from '@/components/Category/Hero'
import Banner from '@/components/Category/Banner'
import Head from 'next/head'
import { useState } from 'react'
import Categories from '@/components/Categories'
import BringingBanner from '@/components/BringingBanner'
import Footer from '@/components/Footer'

const earphones = () => {

  return (
    <div className='font-main'>
        <Head>
            <title>Audiophile | Speakers</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <div className='bg-black pb-3' >
        <div className='bg-white/30 h-[1px]  w-[95%] md:w-[85%] mx-auto  ' />
        </div>
        <Hero title='earphones' />
        <Banner 
            img={'https://audiophile-gamma.vercel.app/assets/product-yx1-earphones/desktop/image-product.jpg'}
            title={'YX1 Wireless Earphones'}
            text={'Tailor your listening experience with bespoke dynamic drivers from the new YX1 Wireless Earphones. Enjoy incredible high-fidelity sound even in noisy environments with its active noise cancellation feature.'}
            slug={'/yx1-earphones'}
            rev={false}
        />
        <Categories />
        <BringingBanner />
        <Footer />
    </div>
  )
}

export default earphones