import Image from 'next/image'

import Head from 'next/head'
import BringingBanner from '../components/BringingBanner'
import Categories from '../components/Categories'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Hero from '../components/Home/Hero'
import YXOneBanner from '../components/Home/YXOneBanner'
import ZXNineBanner from '../components/Home/ZXNineBanner'
import ZXSevenBanner from '../components/Home/ZXSevenBanner'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Audiophile | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
      <Categories />
      <ZXNineBanner />
      <ZXSevenBanner />
      <YXOneBanner />
      <BringingBanner />
      <Footer />
    </div>
  )
}

        {/* <Image
          className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
          src="/next.svg"
          alt="Next.js Logo"
          width={180}
          height={37}
          priority
        /> */}